<%@ Page Title="" Language="C#" MasterPageFile="~/Menu.Master" AutoEventWireup="true" CodeBehind="courses.aspx.cs" Inherits="Student_register.courses" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Courses:</h1>
    <asp:GridView ID="courseGrid" runat="server" AutoGenerateColumns="False" CssClass="table-condensed" DataKeyNames="id" DataSourceID="allCourses" EmptyDataText="No courses available" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCommand="courseGrid_RowCommand" GridLines="Horizontal" OnRowDataBound="courseGrid_RowDataBound" ValidateRequestMode="Disabled">
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="id" HeaderText="Course ID" InsertVisible="False" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="name" HeaderText="Course name" SortExpression="name" />
            <asp:BoundField DataField="firstname" HeaderText="Teachers firstname" SortExpression="firstname" ReadOnly="True" />
            <asp:BoundField DataField="lastname" HeaderText="Teachers lastname" SortExpression="lastname" ReadOnly="True" />
            <asp:ButtonField ButtonType="Button" CommandName="enroll" Text="Enroll">
            <ControlStyle CssClass="btn" />
            </asp:ButtonField>
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="allCourses" runat="server" ConnectionString="<%$ ConnectionStrings:RegisterConnection %>" 
        SelectCommand="SELECT [courses].[id], [courses].[name], [courses].[teacher_id], [users].[firstname], [users].[lastname] FROM [courses], [users] WHERE [users].[id] = [courses].[teacher_id]"
        DeleteCommand="DELETE FROM [courses] WHERE [id] = @id"
        UpdateCommand="UPDATE [courses] SET [name] = @name WHERE [id] = @id">
        <DeleteParameters>
            <asp:ControlParameter ControlID="courseGrid" Name="id" PropertyName="SelectedDataKey" />
        </DeleteParameters>
    </asp:SqlDataSource>
    <asp:Panel ID="addCoursePanel" runat="server">
        <h1>Add a course:</h1>
        <br />
        <label>Course name: </label>
        <asp:TextBox ID="cName" runat="server" CssClass="form-inline"></asp:TextBox>
    &nbsp;
        <label>Teacher: </label>
        <asp:Label ID="fNameLabel" runat="server"></asp:Label>
        <asp:DropDownList ID="teacherList" runat="server" CssClass="dropdown" DataSourceID="teacherSource" DataTextField="lastname" DataValueField="id" AutoPostBack="True" OnDataBound="teacherList_DataBound" OnSelectedIndexChanged="teacherList_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:Button ID="addButton" runat="server" CssClass="btn" Text="Add" OnClick="addButton_Click" ValidationGroup="add" />
        <br />
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="cName" CssClass="label-danger" ErrorMessage="Course name cannotbe empty." ValidationGroup="add"></asp:RequiredFieldValidator>
     </asp:Panel>
    <asp:SqlDataSource ID="teacherSource" runat="server" ConnectionString="<%$ ConnectionStrings:RegisterConnection %>" SelectCommand="SELECT [id], [firstname], [lastname] FROM [users] WHERE [usertype] = 'teacher'"></asp:SqlDataSource>
</asp:Content>
