using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Student_register
{
    public partial class grades : System.Web.UI.Page
    {
        string connString = ConfigurationManager.ConnectionStrings["RegisterConnection"].ConnectionString;
        protected void Page_Load(object sender, EventArgs e)
        {
            //On page load hides the controls used for adding/editing/removing the grades if you are a student
            string role = Request.Cookies["current_user"]["role"];
            if (role == "student")
            {
                addGradePanel.Visible = false;
                gradesGrid.AutoGenerateDeleteButton = false;
                gradesGrid.AutoGenerateEditButton = false;
            }
            else
            {
                addGradePanel.Visible = true;
                gradesGrid.AutoGenerateDeleteButton = true;
                gradesGrid.AutoGenerateEditButton = true;
            }
            //On page load, connect to the database and selects information about a specific course
            SqlConnection conn = new SqlConnection(connString);
            SqlCommand cmd = new SqlCommand("SELECT courses.id, courses.name, users.firstname, users.lastname FROM courses, users WHERE courses.id = " + Convert.ToInt32(Request.QueryString["course_id"]) + " AND courses.teacher_id = users.id", conn);
            conn.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            if (reader.Read())
            {
                //Sets the retrieves information to the labels to display the the course name and it's teacher
                courseName.Text = reader.GetString(1);
                courseTeacher.Text = "Teacher: " + reader.GetString(2) + " " + reader.GetString(3);
            }
            conn.Close();
        }

        protected void addButton_Click(object sender, EventArgs e)
        {
            //Adds a new entry into the grades table
            DateTime date = new DateTime();
            date = DateTime.Now;
            SqlConnection conn = new SqlConnection(connString);
            SqlCommand cmd = new SqlCommand("INSERT INTO grades(student_id, course_id, grade, grade_date) VALUES(" + int.Parse(Request.QueryString["student_id"]) + ", " + int.Parse(Request.QueryString["course_id"]) + ", " + int.Parse(gradeList.SelectedValue) + ", '" + date + "' )", conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();
            gradesGrid.DataBind();
        }
    }
}