<%@ Page Title="" Language="C#" MasterPageFile="~/Menu.Master" AutoEventWireup="true" CodeBehind="grades.aspx.cs" Inherits="Student_register.grades" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="courseName" runat="server" CssClass="h1"></asp:Label><br />
    <asp:Label ID="courseTeacher" runat="server" CssClass="h4"></asp:Label><br />
    <h2>Grades:</h2>
    <asp:GridView ID="gradesGrid" runat="server" AutoGenerateColumns="False" CssClass="table-condensed" DataKeyNames="id" DataSourceID="gradesSource" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" EmptyDataText="No grades yet">
        <Columns>
            <asp:TemplateField HeaderText="Grade" SortExpression="grade">
                <EditItemTemplate>
                    <asp:DropDownList ID="gradeList1" runat="server" Text='<%# Bind("grade") %>'>
                        <asp:ListItem>0</asp:ListItem>
                        <asp:ListItem>1</asp:ListItem>
                        <asp:ListItem>2</asp:ListItem>
                        <asp:ListItem>3</asp:ListItem>
                        <asp:ListItem>4</asp:ListItem>
                        <asp:ListItem>5</asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("grade") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="grade_date" HeaderText="Date" SortExpression="grade_date" ReadOnly="True" DataFormatString="{0:d}" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="gradesSource" runat="server" ConnectionString="<%$ ConnectionStrings:RegisterConnection %>" 
        SelectCommand="SELECT * FROM grades WHERE student_id = @student_id AND course_id = @course_id"
        DeleteCommand="DELETE FROM grades WHERE id = @id"
        UpdateCommand="UPDATE grades SET grade = @grade WHERE id = @id">
        <SelectParameters>
            <asp:QueryStringParameter Name="student_id" QueryStringField="student_id" />
	        <asp:QueryStringParameter Name="course_id" QueryStringField="course_id" />
        </SelectParameters>
    </asp:SqlDataSource>
    <asp:Panel ID="addGradePanel" runat="server">
        <h1>Add grade:</h1>
        <p>
            <label>Grade:</label>
            <asp:DropDownList ID="gradeList" runat="server" CssClass="dropdown">
                <asp:ListItem>0</asp:ListItem>
                <asp:ListItem>1</asp:ListItem>
                <asp:ListItem>2</asp:ListItem>
                <asp:ListItem>3</asp:ListItem>
                <asp:ListItem>4</asp:ListItem>
                <asp:ListItem>5</asp:ListItem>
            </asp:DropDownList>
            <asp:Button ID="addButton" runat="server" CssClass="btn" OnClick="addButton_Click" Text="Add grade" />
        </p>
    </asp:Panel>

</asp:Content>
