<%@ Page Title="" Language="C#" MasterPageFile="~/Menu.Master" AutoEventWireup="true" CodeBehind="users.aspx.cs" Inherits="Student_register.users" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <h1>Users:</h1>
        <asp:GridView ID="userGrid" runat="server" DataKeyNames="id" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table-condensed" DataSourceID="userDataSource" EmptyDataText="No users currently present" AllowPaging="True">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="User ID" SortExpression="id" ReadOnly="True" />
                <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" />
                <asp:BoundField DataField="psw" HeaderText="Password" SortExpression="psw" />
                <asp:BoundField DataField="firstname" HeaderText="Firstname" SortExpression="firstname" />
                <asp:BoundField DataField="lastname" HeaderText="Lastname" SortExpression="lastname" />
                <asp:BoundField DataField="usertype" HeaderText="Role" SortExpression="usertype" ReadOnly="True" />
            </Columns>
            </asp:GridView>
        <asp:SqlDataSource ID="userDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:RegisterConnection %>" SelectCommand="SELECT [id], [username], [psw], [firstname], [lastname], [usertype] FROM [users] WHERE [usertype] != 'admin'"
            DeleteCommand="DELETE FROM [users] WHERE [id] = @id"
            UpdateCommand="UPDATE [users] SET [username] = @username, [psw] = @psw, [firstname] = @firstname, [lastname] = @lastname WHERE [id] = @id">
            <DeleteParameters>
                <asp:ControlParameter ControlID="userGrid" Name="id" PropertyName="SelectedDataKey" />
            </DeleteParameters>
        </asp:SqlDataSource>
        <h1>Add a user:</h1>
        <br />
        <label>First Name: </label>
        <asp:TextBox ID="fName" runat="server" CssClass="form-inline"></asp:TextBox>
        <label>Last Name: </label>
        <asp:TextBox ID="lName" runat="server" CssClass="form-inline" Height="22px"></asp:TextBox>
        <label>Role: </label>
        <asp:DropDownList ID="roleList" runat="server" CssClass="dropdown">
            <asp:ListItem Value="student">Student</asp:ListItem>
            <asp:ListItem Value="teacher">Teacher</asp:ListItem>
        </asp:DropDownList>
        <asp:Button ID="addButton" runat="server" Text="Add" CssClass="btn" OnClick="addButton_Click" ValidationGroup="add" />
        <br />
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="First Name field cannot be empty!" ControlToValidate="fName" CssClass="label-warning" Display="Dynamic" ValidationGroup="add"></asp:RequiredFieldValidator>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Last Name field cannot be empty!" ControlToValidate="lName" CssClass="label-warning" Display="Dynamic" ValidationGroup="add"></asp:RequiredFieldValidator>
</asp:Content>
